const API='https://script.google.com/macros/s/AKfycbxpX9FNMZZDL72L76vS4keCiWC3xPb79_cMkpcBk0_AqktKHizk7j5A6r53brRN9y9d/exec';
const SHEETS=[['TRT','COBRO','TRT'],['SUR','COBRO','SUR'],['AVATRT','INCIDENCIA','TRT'],['AVASUR','INCIDENCIA','SUR']];let raw=[],filtered=[],charts={},timer=null;
let cfg;try{cfg=JSON.parse(localStorage.getItem('avaCfg')||'{"meta":50000,"umbral":10000,"refresh":60000,"theme":"light"}')}catch(_){cfg={meta:50000,umbral:10000,refresh:60000,theme:'light'}};
function hideSplash(){if(typeof window.forceCloseAvaSplash==='function'){window.forceCloseAvaSplash();return}const sp=document.querySelector('#splash');if(sp){sp.classList.add('hide');setTimeout(()=>sp.remove(),550)}}
function on(sel,event,fn){const el=$(sel);if(el)el.addEventListener(event,fn)}
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>(+n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'}),clean=s=>String(s??'').trim(),lc=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),num=n=>Number(String(n??'').replace(/[$,%\s,]/g,''))||0;
const pick=(o,ks)=>{const m={};Object.keys(o||{}).forEach(k=>m[lc(k)]=o[k]);for(const k of ks){let v=m[lc(k)];if(v!==undefined&&v!==null&&clean(v)!=='')return v}return''};
function parseDate(v){if(!v)return null;if(v instanceof Date)return v;const s=clean(v);let d=new Date(s);if(!isNaN(d)&&d.getFullYear()>2020&&d.getFullYear()<2036)return d;let m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;d=new Date(y,+m[2]-1,+m[1]);if(y>2020&&y<2036)return d}return null}
const route=r=>clean(pick(r,['Origen Destino Anomalía']))||[pick(r,['Origen']),pick(r,['Destino'])].filter(Boolean).join(' → ')||'SIN RUTA';
function normalize(r,clase,empresa,hoja){const d=parseDate(pick(r,clase==='COBRO'?['Fecha Cobro','Fecha del Viaje']:['Fecha Corrida','Fecha Cobro','Fecha']));const rubro=clase==='INCIDENCIA'?(clean(pick(r,['Tipo','Rubro','Categoría']))||'SIN RUBRO'):'RECUPERACIÓN';const costo=clase==='INCIDENCIA'?num(pick(r,['Costo','Por Cobrar','Importe','Monto'])):num(pick(r,['Monto Recuperado','Monto','Importe']));const pendiente=clase==='INCIDENCIA'&&lc(pick(r,['Estatus']))!=='cobrado'?num(pick(r,['Por Cobrar','Costo','Importe'])):0;return{...r,_clase:clase,_empresa:empresa,_hoja:hoja,_fecha:d,_mes:d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'SIN FECHA',_anio:d?String(d.getFullYear()):'SIN FECHA',_rubro:rubro,_monto:costo,_pendiente:pendiente,_estatus:clean(pick(r,['Estatus','Status','Estado']))||'SIN ESTATUS',_conductor:clean(pick(r,['Conductor','Nombre Conductor','Operador']))||'SIN CONDUCTOR',_cajero:clean(pick(r,['Nombre Cajero','Cajero']))||'SIN CAJERO',_autobus:clean(pick(r,['Autobus','Autobús','Unidad']))||'',_folio:clean(pick(r,['Folio Recibo','Reporte','Viaje','Id Viaje']))||'',_anomalia:clean(pick(r,['Anomalía','Anomalia']))||'SIN ANOMALÍA',_ruta:route(r)}}
async function fetchSheet(x){const[h,c,e]=x,res=await fetch(`${API}?accion=datos&hoja=${encodeURIComponent(h)}&_=${Date.now()}`),j=await res.json();return(j.datos||j.data||[]).map(r=>normalize(r,c,e,h))}
async function loadData(){try{setSync('Cargando…');raw=(await Promise.all(SHEETS.map(fetchSheet))).flat();populateFilters();applyFilters();setSync(`Actualizado ${new Date().toLocaleTimeString('es-MX')}`,true);toast('Datos actualizados')}catch(e){console.error(e);setSync('Error al cargar',false,true);toast('Error de conexión')}}
function setSync(t,ok,err){$('#syncText').textContent=t;$('.sync').className='sync '+(ok?'ok':err?'err':'')}
function populateFilters(){for(const[id,key]of[['#fRubro','_rubro'],['#fEstatus','_estatus']]){const s=$(id),cur=s.value,vals=[...new Set(raw.filter(r=>id==='#fRubro'?r._clase==='INCIDENCIA':true).map(r=>r[key]).filter(Boolean))].sort();s.innerHTML=`<option value="TODOS">Todos</option>`+vals.map(v=>`<option>${v}</option>`).join('');s.value=vals.includes(cur)?cur:'TODOS'}}
function applyFilters(){const emp=$('#fEmpresa').value,rub=$('#fRubro').value,est=$('#fEstatus').value,q=lc($('#fSearch').value),de=$('#fDesde').value?new Date($('#fDesde').value+'T00:00:00'):null,ha=$('#fHasta').value?new Date($('#fHasta').value+'T23:59:59'):null;filtered=raw.filter(r=>(emp==='TODAS'||r._empresa===emp)&&(rub==='TODOS'||r._rubro===rub)&&(est==='TODOS'||r._estatus===est)&&(!de||r._fecha>=de)&&(!ha||r._fecha<=ha)&&(!q||lc([r._conductor,r._cajero,r._autobus,r._folio,r._anomalia,r._ruta,r._rubro].join(' ')).includes(q)));renderAll()}
const sum=(a,k='_monto')=>a.reduce((s,r)=>s+(+r[k]||0),0);function group(a,key,value='_monto'){const m={};a.forEach(r=>{const k=typeof key==='function'?key(r):r[key];if(!m[k])m[k]={key:k,total:0,count:0,rows:[]};m[k].total+=+r[value]||0;m[k].count++;m[k].rows.push(r)});return Object.values(m)}
const sorted=(a,mode='total')=>[...a].sort((x,y)=>y[mode]-x[mode]);const honesty=a=>a.filter(r=>r._clase==='INCIDENCIA'&&lc(r._rubro)==='honestidad');
function chart(id,type,data,options={}){if(charts[id])charts[id].destroy();const el=$("#"+id);if(!el)return;const dark=document.body.classList.contains('dark'),text=dark?'#aeb8c8':'#536078',grid=dark?'#202b3b':'#e5eaf2';charts[id]=new Chart(el,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:text,boxWidth:10}},tooltip:{callbacks:{label:c=>`${c.dataset.label||c.label}: ${money(c.raw)}`}}},scales:type==='doughnut'?{}:{x:{ticks:{color:text},grid:{display:false}},y:{beginAtZero:true,ticks:{color:text,callback:v=>Intl.NumberFormat('es-MX',{notation:'compact'}).format(v)},grid:{color:grid}}},...options}})}
function palette(n){return['#8b5cf6','#06b6d4','#10b981','#f59e0b','#ef4444','#ec4899','#3b82f6','#14b8a6','#f97316','#6366f1'].slice(0,n)}
function renderAll(){renderKPIs();renderDashboardCharts();renderRubros();renderHonesty();renderConductores();renderCajeros();renderRoutes();renderTrends();renderInsights();renderTable()}
function renderKPIs(){const cobCajeros=sum(filtered.filter(r=>r._clase==='COBRO')),inc=filtered.filter(r=>r._clase==='INCIDENCIA'),cobOtrasAreas=sum(inc.filter(r=>lc(r._estatus)==='cobrado')),totalCobrado=cobCajeros+cobOtrasAreas,hon=sum(honesty(filtered)),otros=inc.filter(r=>lc(r._rubro)!=='honestidad').length,pend=sum(inc,'_pendiente'),gen=sum(inc),rec=gen?cobCajeros/gen*100:0;$('#kCobrado').textContent=money(totalCobrado);$('#kHonestidad').textContent=money(hon);$('#kOtros').textContent=otros.toLocaleString('es-MX');$('#kAdeudo').textContent=money(pend);$('#kIncidencias').textContent=inc.length.toLocaleString('es-MX');$('#kRec').textContent=rec.toFixed(1)+'%';$('#gaugeValue').textContent=rec.toFixed(1)+'%'}
function renderDashboardCharts(){const cob=sum(filtered.filter(r=>r._clase==='COBRO')),inc=filtered.filter(r=>r._clase==='INCIDENCIA'),gen=sum(inc),rec=Math.min(100,gen?cob/gen*100:0);chart('gaugeChart','doughnut',{labels:['Recuperado','Pendiente'],datasets:[{data:[rec,100-rec],backgroundColor:['#8b5cf6','#dfe4ec'],borderWidth:0,circumference:180,rotation:270,cutout:'74%'}]},{plugins:{legend:{display:false},tooltip:{enabled:false}}});const rg=sorted(group(inc,'_rubro'));chart('rubrosDonut','doughnut',{labels:rg.map(x=>x.key),datasets:[{data:rg.map(x=>x.total),backgroundColor:palette(rg.length),borderWidth:0,cutout:'66%'}]});const monthly=periodByRubros(inc,'_mes',6),ds=monthly.rubros.slice(0,5).map((r,i)=>({label:r,data:monthly.labels.map(l=>monthly.map[l]?.[r]||0),borderColor:palette(6)[i],backgroundColor:palette(6)[i]+'22',fill:true,tension:.35}));chart('trendRubrosChart','line',{labels:monthly.labels,datasets:ds});const ag=sorted(group(inc,'_anomalia'), 'count').slice(0,10);chart('incidenciasChart','bar',{labels:ag.map(x=>x.key),datasets:[{label:'Incidencias',data:ag.map(x=>x.count),backgroundColor:'#ef4444'}]},{indexAxis:'y',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw} incidencias`}}}});const day=new Date().getDate(),last=new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate(),forecast=day?cob/day*last:0,advance=cfg.meta?Math.min(100,cob/cfg.meta*100):0;$('#forecastBox').innerHTML=`<b>${money(forecast)}</b><br>Proyección al cierre del mes<br>Meta: ${money(cfg.meta)} · Avance ${advance.toFixed(1)}%`;$('#forecastProgress').style.width=advance+'%';renderRank('#topCajeros',sorted(group(filtered.filter(r=>r._clase==='COBRO'),'_cajero')).slice(0,10),'cajero','total');renderRank('#topConductores',sorted(group(inc,'_conductor'),'count').slice(0,10),'conductor','count')}
function periodByRubros(a,key,limit=12){const map={},rs=[...new Set(a.map(r=>r._rubro))];a.forEach(r=>{if(r[key]==='SIN FECHA')return;map[r[key]]??={};map[r[key]][r._rubro]=(map[r[key]][r._rubro]||0)+r._monto});return{map,rubros:rs,labels:Object.keys(map).sort().slice(-limit)}}
function renderRubros(){const inc=filtered.filter(r=>r._clase==='INCIDENCIA'),g=sorted(group(inc,'_rubro'),'count'),totalInc=g.reduce((a,x)=>a+x.count,0);chart('rubrosChart','pie',{labels:g.map(x=>x.key),datasets:[{label:'Incidencias',data:g.map(x=>x.count),backgroundColor:palette(g.length),borderColor:'rgba(255,255,255,.9)',borderWidth:2,hoverOffset:10}]},{plugins:{legend:{position:'right',labels:{boxWidth:14,usePointStyle:true}},tooltip:{callbacks:{label:c=>{const n=Number(c.raw||0),pct=totalInc?((n/totalInc)*100).toFixed(1):'0.0';return `${c.label}: ${n.toLocaleString('es-MX')} incidencias (${pct}%)`}}}}});chart('rubrosCountChart','bar',{labels:g.map(x=>x.key),datasets:[{label:'Número de incidencias',data:g.map(x=>x.count),backgroundColor:palette(g.length),borderRadius:8}]},{indexAxis:'y',plugins:{tooltip:{callbacks:{label:c=>`${Number(c.raw||0).toLocaleString('es-MX')} incidencias`}}}});$('#rubrosList').innerHTML=g.map(x=>{const esHonestidad=String(x.key||'').trim().toUpperCase()==='HONESTIDAD';return `<div class="entity"><b>${x.key}</b><span>${x.count.toLocaleString('es-MX')} incidencias</span>${esHonestidad?`<br><strong>${money(x.total)}</strong><small>Importe generado</small>`:'<br><strong>'+x.count.toLocaleString('es-MX')+'</strong><small>Número de incidencias</small>'}</div>`}).join('')||'<p>Sin datos</p>'}
function renderHonesty(){const h=honesty(filtered),ag=sorted(group(h,'_anomalia'),'count').slice(0,10),pl=sorted(group(h,'_ruta'),'count').slice(0,10),dr=sorted(group(h,'_conductor'),'count').slice(0,10);chart('honestyIncChart','bar',{labels:ag.map(x=>x.key),datasets:[{label:'Incidencias',data:ag.map(x=>x.count),backgroundColor:'#ef4444'}]},{indexAxis:'y',plugins:{tooltip:{callbacks:{label:c=>`${c.raw} incidencias`}}}});chart('honestyPlacesChart','bar',{labels:pl.map(x=>x.key),datasets:[{label:'Incidencias',data:pl.map(x=>x.count),backgroundColor:'#f59e0b'}]},{indexAxis:'y',plugins:{tooltip:{callbacks:{label:c=>`${c.raw} incidencias`}}}});renderRank('#honestyDrivers',dr,'conductor','count');const pg=periodByRubros(h,'_mes',12);chart('honestyTrendChart','line',{labels:pg.labels,datasets:[{label:'Importe Honestidad',data:pg.labels.map(l=>sum(h.filter(r=>r._mes===l))),borderColor:'#8b5cf6',backgroundColor:'#8b5cf622',fill:true,tension:.35}]})}
function renderRank(sel,data,type,mode='total'){const max=Math.max(...data.map(x=>x[mode]),1);$(sel).innerHTML=data.map((d,i)=>`<div class="rank-row" data-type="${type}" data-key="${d.key}"><b>${['🥇','🥈','🥉'][i]||'#'+(i+1)}</b><div><strong>${d.key}</strong><div class="bar"><i style="width:${d[mode]/max*100}%"></i></div><small>${d.count} registros</small></div><b>${mode==='count'?d.count:money(d.total)}</b></div>`).join('')||'<p>Sin datos</p>'}
function renderConductores(){const inc=filtered.filter(r=>r._clase==='INCIDENCIA'),byCount=sorted(group(inc,'_conductor'),'count').slice(0,10),byAmt=sorted(group(inc,'_conductor')).slice(0,10);renderRank('#driversRank',byCount,'conductor','count');renderRank('#driversAmountRank',byAmt,'conductor');$('#driversList').innerHTML=sorted(group(inc,'_conductor'),'count').slice(0,100).map(d=>`<div class="entity" data-type="conductor" data-key="${d.key}"><b>${d.key}</b><span>${d.count} incidencias</span><br><strong>${money(d.total)}</strong></div>`).join('')}
function renderCajeros(){const g=sorted(group(filtered.filter(r=>r._clase==='COBRO'),'_cajero')).slice(0,15);chart('cashiersChart','bar',{labels:g.map(x=>x.key),datasets:[{label:'Recuperado',data:g.map(x=>x.total),backgroundColor:'#10b981'}]},{indexAxis:'y'});renderRank('#cashiersList',g,'cajero')}
function renderRoutes(){const inc=filtered.filter(r=>r._clase==='INCIDENCIA'),cnt=sorted(group(inc,'_ruta'),'count').slice(0,12),amt=sorted(group(inc,'_ruta')).slice(0,12);chart('routesCountChart','bar',{labels:cnt.map(x=>x.key),datasets:[{label:'Incidencias',data:cnt.map(x=>x.count),backgroundColor:'#f59e0b'}]},{indexAxis:'y',plugins:{tooltip:{callbacks:{label:c=>`${c.raw} incidencias`}}}});chart('routesAmountChart','bar',{labels:amt.map(x=>x.key),datasets:[{label:'Importe',data:amt.map(x=>x.total),backgroundColor:'#8b5cf6'}]},{indexAxis:'y'})}
function renderTrends(){const inc=filtered.filter(r=>r._clase==='INCIDENCIA'),m=periodByRubros(inc,'_mes',12),a=periodByRubros(inc,'_anio',8),tops=sorted(group(inc,'_rubro')).slice(0,6).map(x=>x.key);chart('monthlyRubrosChart','line',{labels:m.labels,datasets:tops.map((r,i)=>({label:r,data:m.labels.map(l=>m.map[l]?.[r]||0),borderColor:palette(6)[i],backgroundColor:palette(6)[i]+'22',tension:.3}))});chart('annualRubrosChart','bar',{labels:a.labels,datasets:tops.map((r,i)=>({label:r,data:a.labels.map(l=>a.map[l]?.[r]||0),backgroundColor:palette(6)[i]}))});const st=sorted(group(inc,'_estatus'),'count');chart('statusChart','doughnut',{labels:st.map(x=>x.key),datasets:[{data:st.map(x=>x.count),backgroundColor:palette(st.length),borderWidth:0,cutout:'62%'}]},{plugins:{tooltip:{callbacks:{label:c=>`${c.label}: ${c.raw} incidencias`}}}})}
function renderInsights(){const cob=sum(filtered.filter(r=>r._clase==='COBRO')),inc=filtered.filter(r=>r._clase==='INCIDENCIA'),hon=honesty(filtered),topCash=sorted(group(filtered.filter(r=>r._clase==='COBRO'),'_cajero'))[0],topDriver=sorted(group(inc,'_conductor'),'count')[0],topHon=sorted(group(hon,'_anomalia'),'count')[0],topPlace=sorted(group(hon,'_ruta'),'count')[0],topRubro=sorted(group(inc,'_rubro'))[0];$('#insightsBox').innerHTML=[`Los cajeros han recuperado <b>${money(cob)}</b> en el periodo seleccionado.`,topCash?`El cajero con mayor recuperación es <b>${topCash.key}</b> con ${money(topCash.total)}.`:'No hay cobros.',`Los conductores generaron <b>${money(sum(inc))}</b> en ${inc.length} incidencias.`,topRubro?`El rubro con mayor importe es <b>${topRubro.key}</b> con ${money(topRubro.total)}.`:'No hay rubros.',topDriver?`El conductor con más incidencias es <b>${topDriver.key}</b> con ${topDriver.count} registros.`:'',topHon?`La incidencia de Honestidad más frecuente es <b>${topHon.key}</b> (${topHon.count}).`:'',topPlace?`El lugar con más incidencias de Honestidad es <b>${topPlace.key}</b> (${topPlace.count}).`:'' ].filter(Boolean).map(t=>`<div class="insight">${t}</div>`).join('')}
function renderTable(){const cols=['_clase','_empresa','_rubro','_estatus','_fecha','_conductor','_cajero','_autobus','_folio','_anomalia','_ruta','_monto'];$('#dataTable thead').innerHTML='<tr>'+cols.map(c=>`<th>${c.slice(1)}</th>`).join('')+'</tr>';$('#dataTable tbody').innerHTML=filtered.slice(0,800).map(r=>'<tr>'+cols.map(c=>`<td>${c==='_fecha'?(r._fecha?r._fecha.toLocaleDateString('es-MX'):''):c==='_monto'?money(r[c]):clean(r[c])}</td>`).join('')+'</tr>').join('')}
function openDetail(type,key){const rows=filtered.filter(r=>type==='conductor'?r._conductor===key:type==='cajero'?r._cajero===key:false);$('#detailContent').innerHTML=`<h2>${key}</h2><div class="kpi"><span>Total</span><b>${money(sum(rows))}</b><small>${rows.length} registros</small></div>`+rows.slice(0,100).map(r=>`<div class="alert"><b>${r._rubro}</b> · ${money(r._monto)}<br><small>${r._fecha?r._fecha.toLocaleDateString('es-MX'):''} · ${r._anomalia} · ${r._ruta}</small></div>`).join('');$('#detailPanel').classList.add('open')}
function exportCSV(){const h=['Clase','Empresa','Rubro','Estatus','Fecha','Conductor','Cajero','Autobus','Folio','Anomalia','Ruta','Monto'],rows=filtered.map(r=>[r._clase,r._empresa,r._rubro,r._estatus,r._fecha?r._fecha.toLocaleDateString('es-MX'):'',r._conductor,r._cajero,r._autobus,r._folio,r._anomalia,r._ruta,r._monto]),csv=[h,...rows].map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');download(new Blob([csv],{type:'text/csv'}),'reporte-ava.csv')}
function exportExcel(){const data=filtered.map(r=>({Clase:r._clase,Empresa:r._empresa,Rubro:r._rubro,Estatus:r._estatus,Fecha:r._fecha?r._fecha.toLocaleDateString('es-MX'):'',Conductor:r._conductor,Cajero:r._cajero,Autobus:r._autobus,Folio:r._folio,Anomalia:r._anomalia,Ruta:r._ruta,Monto:r._monto})),w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.json_to_sheet(data),'AVA');XLSX.writeFile(w,'reporte-ava.xlsx')}
async function exportPDF(){const{jsPDF}=window.jspdf,canvas=await html2canvas($('#captureArea'),{scale:1.1,useCORS:true}),pdf=new jsPDF('p','mm','a4'),w=210,h=canvas.height*w/canvas.width;pdf.text('Centro de Inteligencia AVA',14,12);pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,18,w,h);pdf.save('reporte-ava.pdf')}
function download(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();URL.revokeObjectURL(a.href)}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function setup(){
  try{
    window.addEventListener('error',e=>{console.error('AVA runtime error:',e.error||e.message);hideSplash()});
    window.addEventListener('unhandledrejection',e=>{console.error('AVA promise error:',e.reason);hideSplash()});
    document.body.className=cfg.theme==='dark'?'dark':'light';
    if($('#cfgMeta')) $('#cfgMeta').value=cfg.meta;
    if($('#cfgUmbral')) $('#cfgUmbral').value=cfg.umbral;
    if($('#cfgRefresh')) $('#cfgRefresh').value=cfg.refresh;
    $$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));const target=$('#'+b.dataset.view);if(target)target.classList.add('active');if($('#pageTitle'))$('#pageTitle').textContent=b.textContent.trim().replace(/^[^A-Za-zÁÉÍÓÚÑ]+/,'')});
    ['#fEmpresa','#fRubro','#fEstatus','#fDesde','#fHasta','#fSearch'].forEach(sel=>{const el=$(sel);if(el)el.addEventListener('input',applyFilters)});
    on('#clearBtn','click',()=>{$('#fEmpresa').value='TODAS';$('#fRubro').value='TODOS';$('#fEstatus').value='TODOS';$('#fDesde').value='';$('#fHasta').value='';$('#fSearch').value='';applyFilters()});
    on('#themeBtn','click',()=>{document.body.classList.toggle('dark');document.body.classList.toggle('light');cfg.theme=document.body.classList.contains('dark')?'dark':'light';localStorage.setItem('avaCfg',JSON.stringify(cfg));if(raw.length)renderAll()});
    on('#refreshBtn','click',loadData);
    on('#saveCfg','click',()=>{cfg.meta=num($('#cfgMeta').value);cfg.umbral=num($('#cfgUmbral').value);cfg.refresh=num($('#cfgRefresh').value);localStorage.setItem('avaCfg',JSON.stringify(cfg));startTimer();if(raw.length)renderAll();toast('Configuración guardada')});
    on('#csvBtn','click',exportCSV);on('#excelBtn','click',exportExcel);on('#pdfBtn','click',exportPDF);on('#pdfBtn2','click',exportPDF);
    on('#closeDetail','click',()=>$('#detailPanel')?.classList.remove('open'));
    document.body.addEventListener('click',e=>{const x=e.target.closest('[data-type][data-key]');if(x)openDetail(x.dataset.type,x.dataset.key)});
    setTimeout(hideSplash,900);
    startTimer();
    loadData().catch(console.error).finally(()=>setTimeout(hideSplash,120));
  }catch(e){console.error('No se pudo iniciar AVA:',e);hideSplash();setSync('Error de inicio',false,true)}
}
function startTimer(){if(timer)clearInterval(timer);if(cfg.refresh>0)timer=setInterval(loadData,cfg.refresh)}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',setup,{once:true})}else{setup()}

/* =========================================================
   AUTOBÚS DE AYUDA — asistente local basado en datos cargados
   ========================================================= */
function helpEscape(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function helpRows(){return filtered.length?filtered:raw}
function helpTopRows(rows,key,mode='total',limit=5){return sorted(group(rows,key),mode).filter(x=>x.key&& !String(x.key).startsWith('SIN ')).slice(0,limit)}
function helpAddMessage(role,html){const box=$('#helpChatMessages');if(!box)return;const item=document.createElement('div');item.className=`help-msg ${role}`;item.innerHTML=`<div class="help-bubble">${html}</div>`;box.appendChild(item);box.scrollTop=box.scrollHeight;return item}
function helpWelcome(){const box=$('#helpChatMessages');if(!box||box.children.length)return;helpAddMessage('bot',`¡Hola! Soy el <b>Autobús de Ayuda AVA</b>. Puedo ayudarte a interpretar los indicadores y consultar los datos visibles del portal.<br><br>Prueba con preguntas como:<ul class="help-answer-list"><li>¿Cuál es el total cobrado?</li><li>¿Quién es el cajero que más recuperó?</li><li>¿Qué conductor tiene más incidencias?</li><li>¿Dónde ocurre más Honestidad?</li></ul><div class="help-data-note">Trabajo con los filtros que estén activos.</div>`)}
function helpFormatRanking(items,mode='total',noun='registros'){if(!items.length)return 'No encontré datos para esa consulta con los filtros actuales.';return `<ol class="help-answer-list">${items.map(x=>`<li><b>${helpEscape(x.key)}</b> — ${mode==='total'?money(x.total):`${x.count.toLocaleString('es-MX')} ${noun}`}</li>`).join('')}</ol>`}
function helpSpecificEntity(q,rows){
  const search=lc(q.replace(/^(conductor|cajero|autobus|autobús|folio|ruta)\s*/i,''));
  if(search.length<2)return null;
  const matches=rows.filter(r=>lc([r._conductor,r._cajero,r._autobus,r._folio,r._ruta].join(' ')).includes(search));
  if(!matches.length)return null;
  const inc=matches.filter(r=>r._clase==='INCIDENCIA'),cob=matches.filter(r=>r._clase==='COBRO');
  const name=matches[0]._conductor!=='SIN CONDUCTOR'&&lc(matches[0]._conductor).includes(search)?matches[0]._conductor:matches[0]._cajero!=='SIN CAJERO'&&lc(matches[0]._cajero).includes(search)?matches[0]._cajero:matches[0]._autobus||matches[0]._folio||matches[0]._ruta;
  return `<b>${helpEscape(name)}</b><ul class="help-answer-list"><li>${matches.length.toLocaleString('es-MX')} registros encontrados</li><li>${inc.length.toLocaleString('es-MX')} incidencias por ${money(sum(inc))}</li><li>${cob.length.toLocaleString('es-MX')} cobros por ${money(sum(cob))}</li><li>Pendiente: ${money(sum(inc,'_pendiente'))}</li></ul>`;
}
function helpAnswer(question){
  const q=lc(question),rows=helpRows(),inc=rows.filter(r=>r._clase==='INCIDENCIA'),cobros=rows.filter(r=>r._clase==='COBRO'),hon=honesty(rows),otrasCobradas=inc.filter(r=>lc(r._estatus)==='cobrado');
  if(!rows.length)return 'Todavía no hay datos disponibles. Espera a que termine la carga o pulsa <b>Actualizar</b>.';
  const specific=helpSpecificEntity(q,rows);if(specific&&/(conductor|cajero|autobus|autobús|folio|ruta|buscar|consulta)/.test(q))return specific;
  if(/(hola|buenas|ayuda|que puedes|qué puedes|como funciona|cómo funciona)/.test(q))return `Puedo responder sobre <b>cobros, cajeros, conductores, Honestidad, rubros, rutas, estatus, autobuses y folios</b>. También puedo indicarte dónde encontrar cada módulo del portal.`;
  if(/(total cobrado|cuanto se ha cobrado|cuánto se ha cobrado|cobrado general)/.test(q)){const caj=sum(cobros),otras=sum(otrasCobradas),total=caj+otras;return `El <b>total cobrado general</b> es ${money(total)}.<ul class="help-answer-list"><li>Cobrado por cajeros: ${money(caj)}</li><li>Cobrado por otras áreas: ${money(otras)}</li></ul>`}
  if(/(recuperado por cajero|cobrado por cajero|recuperacion de cajeros|recuperación de cajeros)/.test(q))return `Los cajeros han recuperado <b>${money(sum(cobros))}</b> en ${cobros.length.toLocaleString('es-MX')} movimientos.`;
  if(/(top.*cajero|mejor cajero|cajero.*mas|cajero.*más|ranking.*cajero)/.test(q))return `<b>Top de cajeros por recuperación</b>${helpFormatRanking(helpTopRows(cobros,'_cajero','total',10),'total')}`;
  if(/(top.*conductor|conductor.*mas incidencia|conductor.*más incidencia|ranking.*conductor)/.test(q))return `<b>Conductores con más incidencias generales</b>${helpFormatRanking(helpTopRows(inc,'_conductor','count',10),'count','incidencias')}`;
  if(/(honestidad.*gener|generado.*honestidad|importe.*honestidad|cuanto.*honestidad|cuánto.*honestidad)/.test(q))return `Las incidencias de <b>Honestidad</b> generan ${money(sum(hon))} en ${hon.length.toLocaleString('es-MX')} registros.`;
  if(/(top.*honestidad|incidencia.*honestidad|honestidad.*frecuente)/.test(q))return `<b>Incidencias de Honestidad más frecuentes</b>${helpFormatRanking(helpTopRows(hon,'_anomalia','count',10),'count','incidencias')}`;
  if(/(donde.*honestidad|dónde.*honestidad|lugar.*honestidad|ruta.*honestidad)/.test(q))return `<b>Lugares o rutas con más incidencias de Honestidad</b>${helpFormatRanking(helpTopRows(hon,'_ruta','count',10),'count','incidencias')}`;
  if(/(pendiente|por cobrar|adeudo)/.test(q))return `El importe <b>pendiente por cobrar</b> es ${money(sum(inc,'_pendiente'))}, distribuido en ${inc.filter(r=>r._pendiente>0).length.toLocaleString('es-MX')} registros.`;
  if(/(porcentaje|%.*recuper|recuperacion|recuperación)/.test(q)){const gen=sum(inc),rec=gen?sum(cobros)/gen*100:0;return `El porcentaje de recuperación de cajeros frente al importe generado es <b>${rec.toFixed(1)}%</b>.`}
  if(/(rubros|rubro)/.test(q)){const g=helpTopRows(inc,'_rubro','count',10);return `<b>Incidencias por rubro</b>${helpFormatRanking(g,'count','incidencias')}`}
  if(/(estatus|status|estado)/.test(q)){const g=helpTopRows(inc,'_estatus','count',10);return `<b>Distribución por estatus</b>${helpFormatRanking(g,'count','registros')}`}
  if(/(ruta|origen|destino|lugar)/.test(q)){const g=helpTopRows(inc,'_ruta','count',10);return `<b>Rutas con más incidencias</b>${helpFormatRanking(g,'count','incidencias')}`}
  if(/(otros rubros|diferentes.*honestidad|fuera.*honestidad)/.test(q)){const others=inc.filter(r=>lc(r._rubro)!=='honestidad');return `Hay <b>${others.length.toLocaleString('es-MX')}</b> incidencias en rubros distintos a Honestidad.`}
  if(/(resumen|panorama|situacion|situación)/.test(q)){const topCash=helpTopRows(cobros,'_cajero','total',1)[0],topDriver=helpTopRows(inc,'_conductor','count',1)[0],topPlace=helpTopRows(hon,'_ruta','count',1)[0];return `<b>Resumen del periodo filtrado</b><ul class="help-answer-list"><li>Total cobrado: ${money(sum(cobros)+sum(otrasCobradas))}</li><li>Generado en Honestidad: ${money(sum(hon))}</li><li>Pendiente: ${money(sum(inc,'_pendiente'))}</li>${topCash?`<li>Mejor cajero: ${helpEscape(topCash.key)} (${money(topCash.total)})</li>`:''}${topDriver?`<li>Conductor con más incidencias: ${helpEscape(topDriver.key)} (${topDriver.count})</li>`:''}${topPlace?`<li>Lugar con más Honestidad: ${helpEscape(topPlace.key)} (${topPlace.count})</li>`:''}</ul>`}
  if(/(modulo|módulo|donde veo|dónde veo|navegar)/.test(q))return `Usa la barra lateral: <b>Rubros</b> para distribución, <b>Honestidad</b> para sus tendencias, <b>Conductores</b> y <b>Cajeros</b> para rankings, <b>Rutas</b> para origen-destino, <b>Tendencias</b> para comparativos y <b>Reportes</b> para exportar.`;
  return `No identifiqué completamente la consulta. Puedes preguntar, por ejemplo: <b>“top cajeros”</b>, <b>“total cobrado”</b>, <b>“top conductores”</b>, <b>“lugares de Honestidad”</b>, <b>“incidencias por rubro”</b> o escribir el nombre de un conductor, cajero, autobús o folio.`;
}
function helpAsk(question){const text=clean(question);if(!text)return;helpAddMessage('user',helpEscape(text));const typing=helpAddMessage('bot','<span class="help-typing"><i></i><i></i><i></i></span>');setTimeout(()=>{typing?.remove();helpAddMessage('bot',helpAnswer(text))},320)}
function setupHelpChat(){
  const panel=$('#helpChat'),input=$('#helpChatInput');if(!panel)return;
  const open=()=>{panel.classList.add('open');panel.setAttribute('aria-hidden','false');helpWelcome();setTimeout(()=>input?.focus(),180)};
  const close=()=>{panel.classList.remove('open');panel.setAttribute('aria-hidden','true')};
  on('#helpBusBtn','click',()=>panel.classList.contains('open')?close():open());on('#helpChatClose','click',close);
  on('#helpChatForm','submit',e=>{e.preventDefault();helpAsk(input.value);input.value=''});
  $$('#helpSuggestions [data-question]').forEach(btn=>btn.addEventListener('click',()=>helpAsk(btn.dataset.question)));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))close()});
}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',setupHelpChat,{once:true})}else{setupHelpChat()}
