const API='https://script.google.com/macros/s/AKfycbxpX9FNMZZDL72L76vS4keCiWC3xPb79_cMkpcBk0_AqktKHizk7j5A6r53brRN9y9d/exec';
const SHEETS=[['TRT','COBRADO','TRT'],['SUR','COBRADO','SUR'],['AVATRT','ADEUDO','TRT'],['AVASUR','ADEUDO','SUR']];
let raw=[], filtered=[], charts={}, refreshTimer=null;
const $=id=>document.getElementById(id);
const fmt=n=>(Number(n)||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const pct=n=>`${(Number(n)||0).toFixed(1)}%`;
const clean=s=>String(s??'').trim();
const lower=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function pick(o,names){const ks=Object.keys(o||{});for(const n of names){let k=ks.find(x=>lower(x)===lower(n)); if(k) return o[k]; k=ks.find(x=>lower(x).includes(lower(n))); if(k) return o[k];} return ''}
function money(v){if(typeof v==='number')return v; return Number(String(v||'').replace(/[$,\s]/g,'').replace('−','-'))||0}
function parseDate(v){ if(!v)return null; if(v instanceof Date)return v; if(typeof v==='number'){const d=new Date(Math.round((v-25569)*86400*1000)); return validDate(d)?d:null} let s=String(v).trim(); let d=new Date(s); if(validDate(d))return d; let m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})/); if(m){let y=+m[3]; if(y<100)y+=2000; d=new Date(y,+m[2]-1,+m[1]); if(validDate(d))return d} return null}
function validDate(d){return d instanceof Date&&!isNaN(d)&&d.getFullYear()>=2020&&d.getFullYear()<=2035}
function periodKey(d,type='month'){return type==='year'?String(d.getFullYear()):`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function normalize(row,sheet,tipo,empresa){const fecha=parseDate(pick(row,['Fecha del Viaje','Fecha Corrida','Fecha Cobro','Fecha','FECHA'])); const monto= tipo==='ADEUDO'?money(pick(row,['Por Cobrar','Monto Adeudo','Adeudo','Monto Recuperado','Importe'])):money(pick(row,['Monto Recuperado','Monto','Importe','Por Cobrar'])); const origen=pick(row,['Origen','ORIGEN']); const destino=pick(row,['Destino','DESTINO']); return {...row,sheet,tipo,empresa,fecha,monto,conductor:clean(pick(row,['Conductor','Nombre Conductor','Operador'])),cajero:clean(pick(row,['Nombre Cajero','Cajero','Cajero Cobro'])),autobus:clean(pick(row,['Autobús','Autobus','Unidad'])),folio:clean(pick(row,['Viaje','Folio','Folio AVA'])),estatus:clean(pick(row,['Estatus','Status','Estado']))|| (tipo==='ADEUDO'?'Pendiente':'Cobrado'),ruta:[origen,destino].filter(Boolean).join(' → ')||'Sin ruta'} }
async function load(){try{setSync('● Cargando datos'); const parts=await Promise.all(SHEETS.map(async ([h,t,e])=>{const r=await fetch(`${API}?accion=datos&hoja=${encodeURIComponent(h)}&t=${Date.now()}`); const j=await r.json(); return (j.datos||[]).map(x=>normalize(x,h,t,e));})); raw=parts.flat().filter(x=>x.monto||x.conductor||x.cajero); fillStatus(); applyFilters(); setSync('● Actualizado '+new Date().toLocaleTimeString('es-MX'));}catch(e){console.error(e);setSync('● Error de conexión'); alert('No se pudieron cargar los datos. Revisa permisos del Apps Script o conexión.');} finally{setTimeout(()=>{$('splash').classList.add('hide')},500)}}
function setSync(s){$('syncBadge').textContent=s}
function fillStatus(){const sel=$('estatusFilter'); const val=sel.value; const stats=[...new Set(raw.map(x=>x.estatus).filter(Boolean))].sort(); sel.innerHTML='<option value="TODOS">Todos los estatus</option>'+stats.map(s=>`<option>${s}</option>`).join(''); sel.value=stats.includes(val)?val:'TODOS'}
function applyFilters(){const emp=$('empresaFilter').value,tipo=$('tipoFilter').value,est=$('estatusFilter').value,desde=$('desdeFilter').value?new Date($('desdeFilter').value+'T00:00:00'):null,hasta=$('hastaFilter').value?new Date($('hastaFilter').value+'T23:59:59'):null,q=lower($('globalSearch').value); filtered=raw.filter(x=>(emp==='TODAS'||x.empresa===emp)&&(tipo==='TODOS'||x.tipo===tipo)&&(est==='TODOS'||x.estatus===est)&&(!desde||x.fecha>=desde)&&(!hasta||x.fecha<=hasta)&&(!q||lower([x.conductor,x.cajero,x.autobus,x.folio,x.ruta,x.estatus].join(' ')).includes(q))); renderAll()}
function sum(arr,tipo){return arr.filter(x=>!tipo||x.tipo===tipo).reduce((a,b)=>a+b.monto,0)}
function group(arr,keyFn,valFn=x=>x.monto){const m={}; arr.forEach(x=>{const k=keyFn(x)||'Sin dato'; m[k]=(m[k]||0)+valFn(x)}); return Object.entries(m).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function byPeriod(type){const map={}; filtered.forEach(x=>{if(!x.fecha)return; const k=periodKey(x.fecha,type); map[k]??={periodo:k,cobrado:0,adeudo:0}; map[k][x.tipo==='ADEUDO'?'adeudo':'cobrado']+=x.monto}); return Object.values(map).sort((a,b)=>a.periodo.localeCompare(b.periodo))}
function renderAll(){const cob=sum(filtered,'COBRADO'), ade=sum(filtered,'ADEUDO'), total=cob+ade, rec=total?cob/total*100:0; $('kpiCobrado').textContent=fmt(cob); $('kpiAdeudo').textContent=fmt(ade); $('kpiRecuperacion').textContent=pct(rec); $('gaugeValue').textContent=pct(rec); $('kpiPronostico').textContent=fmt(forecast()); $('deltaCobrado').textContent=`${filtered.filter(x=>x.tipo==='COBRADO').length} registros`; $('deltaAdeudo').textContent=`${filtered.filter(x=>x.tipo==='ADEUDO').length} pendientes`; renderCharts(cob,ade,rec); renderRankings(); renderAlerts(); renderTables(); renderHeatmap(); renderSummary();}
function forecast(){const now=new Date(); const month=filtered.filter(x=>x.tipo==='COBRADO'&&x.fecha&&x.fecha.getMonth()===now.getMonth()&&x.fecha.getFullYear()===now.getFullYear()); const today=now.getDate(); const days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(); return sum(month)/Math.max(today,1)*days}
function chart(id,type,data,options={}){if(charts[id])charts[id].destroy(); charts[id]=new Chart($(id),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,labels:{color:getComputedStyle(document.body).getPropertyValue('--text')}}},scales:type==='doughnut'?{}:{x:{ticks:{color:'#8b90a2'},grid:{display:false}},y:{ticks:{color:'#8b90a2'},grid:{color:'rgba(140,140,160,.14)'}}},...options}})}
function gradient(ctx,a,b){const g=ctx.chart.ctx.createLinearGradient(0,0,0,300);g.addColorStop(0,a);g.addColorStop(1,b);return g}
function renderCharts(cob,ade,rec){chart('gaugeChart','doughnut',{labels:['Recuperación','Pendiente'],datasets:[{data:[rec,100-rec],cutout:'78%',rotation:270,circumference:180,borderWidth:0,backgroundColor:['#8b5cf6','rgba(148,163,184,.22)']}]},{plugins:{legend:{display:false},tooltip:{enabled:false}}}); chart('donutChart','doughnut',{labels:['Cobrado','Adeudo'],datasets:[{data:[cob,ade],cutout:'68%',borderWidth:0,backgroundColor:['#10b981','#ef4444']}]}); $('donutLegend').innerHTML=`<b>Cobrado:</b> ${fmt(cob)} <b>Adeudo:</b> ${fmt(ade)}`; const m=byPeriod('month'), y=byPeriod('year'); chart('monthlyChart','bar',{labels:m.map(x=>x.periodo),datasets:[{label:'Cobrado',data:m.map(x=>x.cobrado),backgroundColor:'#10b981'},{label:'Adeudo',data:m.map(x=>x.adeudo),backgroundColor:'#ef4444'}]}); chart('annualChart','bar',{labels:y.map(x=>x.periodo),datasets:[{label:'Cobrado',data:y.map(x=>x.cobrado),backgroundColor:'#8b5cf6'},{label:'Adeudo',data:y.map(x=>x.adeudo),backgroundColor:'#f97316'}]}); const caj=group(filtered.filter(x=>x.tipo==='COBRADO'),x=>x.cajero).slice(0,10); chart('cajerosChart','bar',{labels:caj.map(x=>x.name),datasets:[{label:'Recuperado',data:caj.map(x=>x.value),backgroundColor:'#8b5cf6'}]},{indexAxis:'y'}); const rutas=group(filtered,x=>x.ruta,()=>1).slice(0,10); chart('rutasChart','bar',{labels:rutas.map(x=>x.name),datasets:[{label:'Viajes / registros',data:rutas.map(x=>x.value),backgroundColor:'#06b6d4'}]},{indexAxis:'y'}); const daily={}; filtered.forEach(x=>{if(!x.fecha)return; const k=x.fecha.toISOString().slice(0,10); daily[k]??={cobrado:0,adeudo:0}; daily[k][x.tipo==='ADEUDO'?'adeudo':'cobrado']+=x.monto}); const d=Object.entries(daily).sort().map(([k,v])=>({k,...v})); chart('trendChart','line',{labels:d.map(x=>x.k),datasets:[{label:'Cobrado',data:d.map(x=>x.cobrado),borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.15)',fill:true,tension:.35},{label:'Adeudo',data:d.map(x=>x.adeudo),borderColor:'#ef4444',backgroundColor:'rgba(239,68,68,.12)',fill:true,tension:.35}]});}
function medal(i){return ['🥇','🥈','🥉'][i]||`#${i+1}`}
function renderRankings(){const conduct=group(filtered.filter(x=>x.tipo==='ADEUDO'),x=>x.conductor).slice(0,10); const caj=group(filtered.filter(x=>x.tipo==='COBRADO'),x=>x.cajero).slice(0,10); $('topConductores').innerHTML=rankHtml(conduct,'conductor'); $('topCajeros').innerHTML=rankHtml(caj,'cajero')}
function rankHtml(items,type){const max=items[0]?.value||1; return items.map((x,i)=>`<div class="rank-row" onclick="openDetail('${type}','${encodeURIComponent(x.name)}')"><b>${medal(i)}</b><div><strong>${x.name}</strong><div class="bar"><i style="width:${Math.max(4,x.value/max*100)}%"></i></div></div><b>${fmt(x.value)}</b></div>`).join('')||'<p>Sin datos</p>'}
function renderAlerts(){const umbral=Number(localStorage.umbralAdeudo||5000); const top=group(filtered.filter(x=>x.tipo==='ADEUDO'),x=>x.conductor).filter(x=>x.value>=umbral).slice(0,9); $('alerts').innerHTML=top.map(x=>`<div class="alert"><b>🔔 ${x.name}</b><br><span>Adeudo superior a ${fmt(umbral)}</span><h3>${fmt(x.value)}</h3></div>`).join('')||'<p>Sin alertas con el umbral actual.</p>'}
function renderTables(){const rows=filtered.slice(0,300); const html=table(rows); $('reportTable').innerHTML=html; $('conductoresList').innerHTML=tableSummary(group(filtered,x=>x.conductor),'conductor'); $('cajerosList').innerHTML=tableSummary(group(filtered.filter(x=>x.tipo==='COBRADO'),x=>x.cajero),'cajero'); $('rutasList').innerHTML=tableSummary(group(filtered,x=>x.ruta),'ruta')}
function table(rows){return `<table class="data-table"><thead><tr><th>Tipo</th><th>Empresa</th><th>Fecha</th><th>Conductor</th><th>Cajero</th><th>Autobús</th><th>Ruta</th><th>Estatus</th><th>Monto</th></tr></thead><tbody>${rows.map(x=>`<tr onclick="openRecord('${encodeURIComponent(x.folio+x.conductor+x.monto)}')"><td><span class="pill">${x.tipo}</span></td><td>${x.empresa}</td><td>${x.fecha?x.fecha.toLocaleDateString('es-MX'):''}</td><td>${x.conductor}</td><td>${x.cajero}</td><td>${x.autobus}</td><td>${x.ruta}</td><td>${x.estatus}</td><td>${fmt(x.monto)}</td></tr>`).join('')}</tbody></table>`}
function tableSummary(items,type){return `<table class="data-table"><thead><tr><th>Nombre</th><th>Total</th><th>Acción</th></tr></thead><tbody>${items.slice(0,80).map(x=>`<tr><td>${x.name}</td><td>${fmt(x.value)}</td><td><button class="ghost" onclick="openDetail('${type}','${encodeURIComponent(x.name)}')">Ver historial</button></td></tr>`).join('')}</tbody></table>`}
function renderHeatmap(){const stats=[...new Set(filtered.map(x=>x.estatus).filter(Boolean))]; const caj=[...new Set(filtered.map(x=>x.cajero).filter(Boolean))].slice(0,20); $('heatmap').innerHTML=caj.map(c=>{const total=filtered.filter(x=>x.cajero===c).length||1; const lines=stats.map(s=>`${s}: ${filtered.filter(x=>x.cajero===c&&x.estatus===s).length}`).join('<br>'); return `<div class="heat-cell"><b>${c}</b><br><small>${lines}</small><div class="bar"><i style="width:${Math.min(100,total*8)}%"></i></div></div>`}).join('')||'<p>Sin datos de cajeros.</p>'}
function renderSummary(){const cob=sum(filtered,'COBRADO'),ade=sum(filtered,'ADEUDO'),rec=(cob+ade)?cob/(cob+ade)*100:0; const topC=group(filtered.filter(x=>x.tipo==='COBRADO'),x=>x.cajero)[0]; const topD=group(filtered.filter(x=>x.tipo==='ADEUDO'),x=>x.conductor)[0]; const topR=group(filtered,x=>x.ruta,()=>1)[0]; $('aiSummary').innerHTML=`<h2>🤖 Resumen ejecutivo automático</h2><ul><li>La recuperación actual es de <b>${pct(rec)}</b>, con ${fmt(cob)} cobrado y ${fmt(ade)} pendiente.</li><li>El cajero con mayor recuperación es <b>${topC?.name||'Sin dato'}</b> con <b>${fmt(topC?.value||0)}</b>.</li><li>El conductor con mayor adeudo es <b>${topD?.name||'Sin dato'}</b> con <b>${fmt(topD?.value||0)}</b>.</li><li>El origen-destino más concurrido es <b>${topR?.name||'Sin dato'}</b>, con <b>${topR?.value||0}</b> registros.</li><li>Pronóstico de recuperación al cierre del mes: <b>${fmt(forecast())}</b>.</li></ul>`}
window.openDetail=function(type,nameEnc){const name=decodeURIComponent(nameEnc); let rows=filtered.filter(x=> type==='conductor'?x.conductor===name:type==='cajero'?x.cajero===name:x.ruta===name); $('detailContent').innerHTML=`<h2>${name}</h2><p><b>Cobrado:</b> ${fmt(sum(rows,'COBRADO'))}</p><p><b>Adeudo:</b> ${fmt(sum(rows,'ADEUDO'))}</p><p><b>Registros:</b> ${rows.length}</p>${table(rows.slice(0,80))}`; $('detailPanel').classList.add('open')}
window.openRecord=function(){ }
function exportExcel(){const data=filtered.map(x=>({Tipo:x.tipo,Empresa:x.empresa,Fecha:x.fecha?x.fecha.toLocaleDateString('es-MX'):'',Conductor:x.conductor,Cajero:x.cajero,Autobus:x.autobus,Ruta:x.ruta,Estatus:x.estatus,Monto:x.monto})); const ws=XLSX.utils.json_to_sheet(data); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'Reporte AVA'); XLSX.writeFile(wb,'reporte_ava.xlsx')}
function exportPdf(){html2pdf().set({margin:.35,filename:'reporte_ejecutivo_ava.pdf',html2canvas:{scale:2},jsPDF:{unit:'in',format:'letter',orientation:'landscape'}}).from($('printArea')).save()}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.section').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $(b.dataset.section).classList.add('active'); $('pageTitle').textContent=b.textContent.replace(/[📊🚌💰🗺️📈🤖📄⚙️]/g,'').trim()}); ['empresaFilter','tipoFilter','estatusFilter','desdeFilter','hastaFilter','globalSearch'].forEach(id=>$(id).addEventListener('input',applyFilters)); $('refreshBtn').onclick=load; $('clearFilters').onclick=()=>{['empresaFilter','tipoFilter','estatusFilter'].forEach(id=>$(id).value=id==='empresaFilter'?'TODAS':id==='tipoFilter'?'TODOS':'TODOS');$('desdeFilter').value='';$('hastaFilter').value='';$('globalSearch').value='';applyFilters()}; $('themeBtn').onclick=()=>{document.body.classList.toggle('dark'); localStorage.theme=document.body.classList.contains('dark')?'dark':'light'; renderAll()}; $('excelBtn').onclick=exportExcel; $('pdfBtn').onclick=exportPdf; $('closeDetail').onclick=()=>$('detailPanel').classList.remove('open'); $('saveConfig').onclick=()=>{localStorage.metaMensual=$('metaMensual').value; localStorage.umbralAdeudo=$('umbralAdeudo').value; setAuto(); renderAll(); alert('Configuración guardada')}; $('metaMensual').value=localStorage.metaMensual||50000; $('umbralAdeudo').value=localStorage.umbralAdeudo||5000; $('autoRefresh').value=localStorage.autoRefresh||0; $('autoRefresh').onchange=()=>{localStorage.autoRefresh=$('autoRefresh').value; setAuto()}; if(localStorage.theme==='dark')document.body.classList.add('dark')}
function setAuto(){clearInterval(refreshTimer); const ms=Number($('autoRefresh').value||0); if(ms) refreshTimer=setInterval(load,ms)}
bind(); load(); setAuto();
