const API='https://script.google.com/macros/s/AKfycbxpX9FNMZZDL72L76vS4keCiWC3xPb79_cMkpcBk0_AqktKHizk7j5A6r53brRN9y9d/exec';
const SHEETS=[['TRT','COBRADO','TRT'],['SUR','COBRADO','SUR'],['AVATRT','ADEUDO','TRT'],['AVASUR','ADEUDO','SUR']];
let raw=[],filtered=[],charts={},timer=null;
let cfg=JSON.parse(localStorage.getItem('avaCfg')||'{"meta":50000,"umbral":10000,"refresh":60000,"theme":"light"}');
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=n=>(Number(n)||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const num=n=>Number(n)||0;
const clean=s=>String(s??'').trim();
const lc=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const pick=(o,keys)=>{const map={};Object.keys(o||{}).forEach(k=>map[lc(k)]=o[k]);for(const k of keys){const v=map[lc(k)];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return ''};
const amount=r=>num(String(pick(r,['Monto Recuperado','Por Cobrar','Monto Adeudo','Adeudo','Importe','Monto','Total'])).replace(/[$,]/g,''));
const dateVal=r=>parseDate(pick(r,['Fecha del Viaje','Fecha Corrida','Fecha Cobro','Fecha','Fecha de Viaje']));
const conductor=r=>clean(pick(r,['Conductor','Nombre Conductor','Operador']));
const cajero=r=>clean(pick(r,['Nombre Cajero','Cajero','Cajero Cobro']));
const autobus=r=>clean(pick(r,['Autobús','Autobus','Autobús Corrida','Unidad']));
const estatus=r=>clean(pick(r,['Estatus','Status','Estado']))||'SIN ESTATUS';
const folio=r=>clean(pick(r,['Folio','Viaje','Corrida','No Viaje']));
const origen=r=>clean(pick(r,['Origen','Terminal Origen','Origen Corrida']));
const destino=r=>clean(pick(r,['Destino','Terminal Destino','Destino Corrida']));
function parseDate(v){ if(!v)return null; if(v instanceof Date)return v; const s=String(v).trim(); let d=new Date(s); if(!isNaN(d)&&d.getFullYear()>2020&&d.getFullYear()<2036)return d; const m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})/); if(m){let y=+m[3]; if(y<100)y+=2000; d=new Date(y,+m[2]-1,+m[1]); if(!isNaN(d)&&y>2020&&y<2036)return d} return null; }
function ym(d){return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:'SIN FECHA'} function y(d){return d?String(d.getFullYear()):'SIN FECHA'}
function normalize(r,tipo,empresa,hoja){const d=dateVal(r);return {...r,_tipo:tipo,_empresa:empresa,_hoja:hoja,_monto:amount(r),_fecha:d,_ym:ym(d),_y:y(d),_conductor:conductor(r)||'SIN CONDUCTOR',_cajero:cajero(r)||'SIN CAJERO',_autobus:autobus(r),_estatus:estatus(r),_folio:folio(r),_ruta:[origen(r),destino(r)].filter(Boolean).join(' → ')||'SIN RUTA'}}
async function fetchSheet([hoja,tipo,empresa]){const url=`${API}?accion=datos&hoja=${encodeURIComponent(hoja)}&_=${Date.now()}`; const res=await fetch(url); const json=await res.json(); const datos=json.datos||json.data||[]; return datos.map(r=>normalize(r,tipo,empresa,hoja));}
async function loadData(){try{setSync('Cargando...',false); raw=(await Promise.all(SHEETS.map(fetchSheet))).flat(); populateStatus(); applyFilters(); setSync(`Actualizado ${new Date().toLocaleTimeString('es-MX')}`,true); toast('Datos actualizados');}catch(e){console.error(e);setSync('Error al cargar',false,true);toast('No se pudieron cargar los datos');}}
function setSync(t,ok,err){$('#syncText').textContent=t;$('.sync').className='sync '+(ok?'ok':err?'err':'')}
function populateStatus(){const sel=$('#fEstatus'),cur=sel.value; const vals=[...new Set(raw.map(r=>r._estatus).filter(Boolean))].sort(); sel.innerHTML='<option value="TODOS">Todos</option>'+vals.map(v=>`<option>${v}</option>`).join(''); sel.value=vals.includes(cur)?cur:'TODOS'}
function applyFilters(){const emp=$('#fEmpresa').value,tipo=$('#fTipo').value,est=$('#fEstatus').value,q=lc($('#fSearch').value),desde=$('#fDesde').value?new Date($('#fDesde').value+'T00:00:00'):null,hasta=$('#fHasta').value?new Date($('#fHasta').value+'T23:59:59'):null; filtered=raw.filter(r=>(emp==='TODAS'||r._empresa===emp)&&(tipo==='TODOS'||r._tipo===tipo)&&(est==='TODOS'||r._estatus===est)&&(!desde||r._fecha>=desde)&&(!hasta||r._fecha<=hasta)&&(!q||lc([r._conductor,r._cajero,r._autobus,r._folio,r._ruta,r._estatus].join(' ')).includes(q))); renderAll();}
function sum(arr,tipo){return arr.filter(r=>!tipo||r._tipo===tipo).reduce((a,b)=>a+b._monto,0)} function group(arr,key){const m={};arr.forEach(r=>{const k=typeof key==='function'?key(r):r[key];if(!m[k])m[k]={key:k,total:0,count:0,rows:[]};m[k].total+=r._monto;m[k].count++;m[k].rows.push(r)});return Object.values(m).sort((a,b)=>b.total-a.total)}
function renderAll(){renderKPIs();renderCharts();renderRanks();renderLists();renderRoutes();renderHeatmap();renderInsights();renderTable();}
function renderKPIs(){const cob=sum(filtered,'COBRADO'), ade=sum(filtered,'ADEUDO'), rec=cob+ade?cob/(cob+ade)*100:0, alerts=filtered.filter(r=>r._tipo==='ADEUDO'&&r._monto>=cfg.umbral).length; $('#kCobrado').textContent=money(cob);$('#kAdeudo').textContent=money(ade);$('#kRec').textContent=rec.toFixed(1)+'%';$('#kAlertas').textContent=alerts; $('#kCobradoTrend').textContent=forecastText(cob); $('#kAdeudoTrend').textContent=ade>0?'Pendiente por recuperar':'Sin adeudo';}
function grad(ctx,c1,c2){const g=ctx.createLinearGradient(0,0,0,260);g.addColorStop(0,c1);g.addColorStop(1,c2);return g}
function makeChart(id,type,data,options={}){if(charts[id])charts[id].destroy();const ctx=document.getElementById(id); if(!ctx)return; charts[id]=new Chart(ctx,{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:c=>`${c.dataset.label||c.label}: ${money(c.raw)}`}}},scales:type==='doughnut'?{}:{y:{beginAtZero:true,ticks:{callback:v=>Intl.NumberFormat('es-MX',{notation:'compact'}).format(v)}},x:{grid:{display:false}}},...options}})}
function renderCharts(){const cob=sum(filtered,'COBRADO'),ade=sum(filtered,'ADEUDO'),rec=cob+ade?cob/(cob+ade)*100:0; $('#gaugeValue').textContent=rec.toFixed(1)+'%'; makeChart('gaugeChart','doughnut',{labels:['Recuperado','Pendiente'],datasets:[{data:[rec,100-rec],backgroundColor:['#a855f7','#e5e7eb'],borderWidth:0,circumference:180,rotation:270,cutout:'76%'}]},{plugins:{legend:{display:false},tooltip:{enabled:false}}}); makeChart('donutChart','doughnut',{labels:['Cobrado','Adeudo'],datasets:[{data:[cob,ade],backgroundColor:['#10b981','#ef4444'],borderWidth:0,cutout:'68%'}]}); const mons=periodData('_ym'); makeChart('monthlyChart','bar',{labels:mons.labels,datasets:[{label:'Cobrado',data:mons.cobrado,backgroundColor:'#7c3aed'},{label:'Adeudo',data:mons.adeudo,backgroundColor:'#ec4899'}]}); const yrs=periodData('_y'); makeChart('annualChart','bar',{labels:yrs.labels,datasets:[{label:'Cobrado',data:yrs.cobrado,backgroundColor:'#10b981'},{label:'Adeudo',data:yrs.adeudo,backgroundColor:'#ef4444'}]}); const st=group(filtered,'_estatus').slice(0,8); makeChart('statusChart','doughnut',{labels:st.map(x=>x.key),datasets:[{data:st.map(x=>x.total),backgroundColor:['#7c3aed','#ec4899','#10b981','#f59e0b','#2563eb','#ef4444','#14b8a6','#64748b'],borderWidth:0}]}); const routes=group(filtered,'_ruta').slice(0,8); makeChart('routesChart','bar',{labels:routes.map(x=>x.key),datasets:[{label:'Monto',data:routes.map(x=>x.total),backgroundColor:'#8b5cf6'}]},{indexAxis:'y'});}
function periodData(k){const g={};filtered.forEach(r=>{if(!r._fecha)return; const p=r[k]; if(!g[p])g[p]={c:0,a:0}; if(r._tipo==='COBRADO')g[p].c+=r._monto; else g[p].a+=r._monto}); const labels=Object.keys(g).filter(x=>x!=='SIN FECHA').sort().slice(-12); return {labels,cobrado:labels.map(l=>g[l].c),adeudo:labels.map(l=>g[l].a)}}
function medal(i){return ['🥇','🥈','🥉'][i]||`#${i+1}`}
function renderRank(el,data,clickType){const max=Math.max(...data.map(d=>d.total),1); $(el).innerHTML=data.map((d,i)=>`<div class="rank-row" data-type="${clickType}" data-key="${d.key}"><b>${medal(i)}</b><div><strong>${d.key}</strong><div class="bar"><i style="width:${d.total/max*100}%"></i></div><small>${d.count} registros</small></div><b>${money(d.total)}</b></div>`).join('')||'<p>Sin datos</p>'}
function renderRanks(){renderRank('#topCajeros',group(filtered.filter(r=>r._tipo==='COBRADO'),'_cajero').slice(0,10),'cajero');renderRank('#topConductores',group(filtered.filter(r=>r._tipo==='ADEUDO'),'_conductor').slice(0,10),'conductor'); const alerts=filtered.filter(r=>r._tipo==='ADEUDO'&&r._monto>=cfg.umbral).sort((a,b)=>b._monto-a._monto).slice(0,12); $('#alerts').innerHTML=alerts.map(r=>`<div class="alert">🔔 <b>${r._conductor}</b> supera el umbral con ${money(r._monto)} · ${r._empresa} · ${r._ruta}</div>`).join('')||'<p>Sin alertas críticas.</p>';}
function renderLists(){const drivers=group(filtered,'_conductor').slice(0,80); $('#driversList').innerHTML=drivers.map(d=>`<div class="entity" data-type="conductor" data-key="${d.key}"><b>${d.key}</b><span>${d.count} registros</span><br><strong>${money(d.total)}</strong></div>`).join(''); const cash=group(filtered,'_cajero').slice(0,80); $('#cashiersList').innerHTML=cash.map(d=>`<div class="entity" data-type="cajero" data-key="${d.key}"><b>${d.key}</b><span>${d.count} registros</span><br><strong>${money(d.total)}</strong></div>`).join('');}
function renderRoutes(){renderRank('#routesList',group(filtered,'_ruta').slice(0,20),'ruta')}
function renderHeatmap(){const data=group(filtered,'_cajero').slice(0,24); const max=Math.max(...data.map(d=>d.total),1); $('#heatmap').innerHTML=data.map(d=>{const p=d.total/max;return `<div class="heat ${p>.66?'high':p>.33?'mid':''}"><b>${d.key}</b><br>${money(d.total)}<br><small>${d.count} registros</small></div>`}).join('')||'<p>Sin datos</p>'}
function forecastText(cob){const now=new Date(),day=now.getDate(),last=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(); if(day<1)return '—'; return `Pronóstico mensual: ${money(cob/day*last)}`}
function renderInsights(){const cob=sum(filtered,'COBRADO'),ade=sum(filtered,'ADEUDO'),rec=cob+ade?cob/(cob+ade)*100:0,topC=group(filtered.filter(r=>r._tipo==='COBRADO'),'_cajero')[0],topD=group(filtered.filter(r=>r._tipo==='ADEUDO'),'_conductor')[0],topR=group(filtered,'_ruta')[0]; $('#forecastBox').innerHTML=`<b>${forecastText(cob)}</b><br>Meta configurada: ${money(cfg.meta)}<br>Avance actual: ${cfg.meta?(cob/cfg.meta*100).toFixed(1):0}%`; $('#insightsBox').innerHTML=[`La recuperación actual es de <b>${rec.toFixed(1)}%</b>, con ${money(cob)} cobrados y ${money(ade)} pendientes.`,topC?`El cajero con mayor recuperación es <b>${topC.key}</b> con ${money(topC.total)}.`:'No hay cajeros con cobros en el filtro actual.',topD?`El conductor con mayor adeudo es <b>${topD.key}</b> con ${money(topD.total)}.`:'No hay adeudos en el filtro actual.',topR?`La ruta más relevante es <b>${topR.key}</b> con ${topR.count} registros y ${money(topR.total)}.`:'No hay rutas disponibles.',`Existen <b>${filtered.filter(r=>r._tipo==='ADEUDO'&&r._monto>=cfg.umbral).length}</b> alertas por adeudos superiores a ${money(cfg.umbral)}.`].map(x=>`<div class="insight">${x}</div>`).join('')}
function renderTable(){const cols=['_tipo','_empresa','_estatus','_fecha','_conductor','_cajero','_autobus','_folio','_ruta','_monto']; $('#dataTable thead').innerHTML='<tr>'+cols.map(c=>`<th>${c.replace('_','')}</th>`).join('')+'</tr>'; $('#dataTable tbody').innerHTML=filtered.slice(0,500).map(r=>'<tr>'+cols.map(c=>`<td>${c==='_fecha'?(r._fecha?r._fecha.toLocaleDateString('es-MX'):'') : c==='_monto'?money(r[c]):clean(r[c])}</td>`).join('')+'</tr>').join('')}
function openDetail(type,key){let rows=filtered.filter(r=> type==='conductor'?r._conductor===key:type==='cajero'?r._cajero===key:type==='ruta'?r._ruta===key:false); $('#detailContent').innerHTML=`<h2>${key}</h2><p>${type.toUpperCase()}</p><div class="kpi"><span>Total</span><b>${money(sum(rows))}</b><small>${rows.length} registros</small></div><h3>Historial</h3>`+rows.slice(0,80).map(r=>`<div class="alert"><b>${r._tipo}</b> · ${r._empresa} · ${money(r._monto)}<br><small>${r._fecha?r._fecha.toLocaleDateString('es-MX'):''} · ${r._ruta} · ${r._estatus}</small></div>`).join(''); $('#detailPanel').classList.add('open')}
function exportCSV(){const headers=['Tipo','Empresa','Estatus','Fecha','Conductor','Cajero','Autobus','Folio','Ruta','Monto']; const rows=filtered.map(r=>[r._tipo,r._empresa,r._estatus,r._fecha?r._fecha.toLocaleDateString('es-MX'):'',r._conductor,r._cajero,r._autobus,r._folio,r._ruta,r._monto]); const csv=[headers,...rows].map(a=>a.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'); download(new Blob([csv],{type:'text/csv'}),'reporte-ava.csv')}
function exportExcel(){const data=filtered.map(r=>({Tipo:r._tipo,Empresa:r._empresa,Estatus:r._estatus,Fecha:r._fecha?r._fecha.toLocaleDateString('es-MX'):'',Conductor:r._conductor,Cajero:r._cajero,Autobus:r._autobus,Folio:r._folio,Ruta:r._ruta,Monto:r._monto})); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'Reporte AVA'); XLSX.writeFile(wb,'reporte-ava.xlsx')}
async function exportPDF(){const {jsPDF}=window.jspdf; const canvas=await html2canvas($('#captureArea'),{scale:1.3,useCORS:true}); const pdf=new jsPDF('p','mm','a4'); const img=canvas.toDataURL('image/png'); const w=210,h=canvas.height*w/canvas.width; pdf.text('Reporte Ejecutivo AVA',14,12); pdf.addImage(img,'PNG',0,18,w,h); pdf.save('reporte-ejecutivo-ava.pdf')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)} function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function setup(){if(cfg.theme==='dark')document.body.classList.add('dark'); $('#cfgMeta').value=cfg.meta;$('#cfgUmbral').value=cfg.umbral;$('#cfgRefresh').value=cfg.refresh; $$('.nav').forEach(b=>b.onclick=()=>{$$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');$('#pageTitle').textContent=b.textContent.trim().replace(/^[^\wÁÉÍÓÚÑ]+/,'')}); ['#fEmpresa','#fTipo','#fEstatus','#fDesde','#fHasta','#fSearch'].forEach(s=>$(s).addEventListener('input',applyFilters)); $('#clearBtn').onclick=()=>{$('#fEmpresa').value='TODAS';$('#fTipo').value='TODOS';$('#fEstatus').value='TODOS';$('#fDesde').value='';$('#fHasta').value='';$('#fSearch').value='';applyFilters()}; $('#refreshBtn').onclick=loadData; $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');cfg.theme=document.body.classList.contains('dark')?'dark':'light';localStorage.setItem('avaCfg',JSON.stringify(cfg))}; $('#saveCfg').onclick=()=>{cfg.meta=num($('#cfgMeta').value);cfg.umbral=num($('#cfgUmbral').value);cfg.refresh=num($('#cfgRefresh').value);localStorage.setItem('avaCfg',JSON.stringify(cfg));startTimer();applyFilters();toast('Configuración guardada')}; $('#csvBtn').onclick=exportCSV;$('#excelBtn').onclick=exportExcel;$('#pdfBtn').onclick=exportPDF;$('#pdfBtn2').onclick=exportPDF; $('#closeDetail').onclick=()=>$('#detailPanel').classList.remove('open'); document.body.addEventListener('click',e=>{const row=e.target.closest('[data-type][data-key]'); if(row)openDetail(row.dataset.type,row.dataset.key)}); setTimeout(()=>$('#splash').classList.add('hide'),1200); startTimer(); loadData();}
function startTimer(){if(timer)clearInterval(timer); if(cfg.refresh>0)timer=setInterval(loadData,cfg.refresh)}
setup();
