(function(){
  const $=s=>document.querySelector(s); let parsedFiles={};
  const expected=[{key:'CAJEROS TRT',label:'CAJEROS TRT'},{key:'CAJEROS SUR',label:'CAJEROS SUR'},{key:'TRT',label:'TRT'},{key:'SUR',label:'SUR'}];
  function admin(){return typeof session!=='undefined' && session?.rol==='ADMINISTRADOR'}
  function msg(t,type=''){const e=$('#monthlyUploadMessage');if(e){e.textContent=t;e.className='admin-form-message '+type}}
  function setStatus(){const e=$('#uploadFileStatus');if(!e)return;const lines=expected.map(x=>`${parsedFiles[x.key]?'✓':'○'} ${x.label}${parsedFiles[x.key]?' — '+parsedFiles[x.key].rows.length+' filas':''}`);e.innerHTML=lines.map(t=>`<div>${t.replace(/&/g,'&amp;').replace(/</g,'&lt;')}</div>`).join('')}
  function identify(name){const n=String(name).toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(n.includes('CAJEROS')&&n.includes('TRT'))return 'CAJEROS TRT';if(n.includes('CAJEROS')&&n.includes('SUR'))return 'CAJEROS SUR';if(/(^|[^A-Z])TRT([^A-Z]|$)/.test(n))return 'TRT';if(/(^|[^A-Z])SUR([^A-Z]|$)/.test(n))return 'SUR';return null}
  async function readWorkbook(file){if(!window.XLSX)throw new Error('No se pudo cargar el lector de Excel. Verifica tu conexión e inténtalo de nuevo.');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});const sheet=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});while(rows.length&&rows[rows.length-1].every(v=>String(v??'').trim()===''))rows.pop();if(rows.length<2)throw new Error(file.name+' no contiene encabezados y registros.');return {name:file.name,rows};}
  async function parseFiles(files){parsedFiles={};for(const file of files){const key=identify(file.name);if(!key)continue;if(parsedFiles[key])throw new Error('Hay más de un archivo identificado como '+key+'.');parsedFiles[key]=await readWorkbook(file)}setStatus()}
  async function readZip(file){if(!window.JSZip)throw new Error('No se pudo cargar el lector ZIP.');const zip=await JSZip.loadAsync(file);const excel=Object.keys(zip.files).filter(n=>!zip.files[n].dir&&/\.xlsx?$/i.test(n)&&!n.split('/').pop().startsWith('~$'));if(excel.length!==4)throw new Error('El ZIP debe contener exactamente los cuatro archivos Excel esperados. Se encontraron '+excel.length+'.');const files=[];for(const name of excel){const blob=await zip.files[name].async('blob');files.push(new File([blob],name.split('/').pop(),{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}))}await parseFiles(files)}
  async function checkPeriod(){const mes=$('#uploadMonth').value,anio=$('#uploadYear').value;if(!mes||!anio)throw new Error('Selecciona mes y año.');const j=await apiGet('admin_periodo',{token:session.token,mes,anio});if(j.error)throw new Error(j.mensaje);return j}
  async function submit(e){e.preventDefault();if(!admin()){msg('Esta función requiere una cuenta ADMINISTRADOR.','error');return}const btn=$('#monthlyUploadSubmit');btn.disabled=true;try{msg('Validando los archivos…');const zip=$('#uploadZipFile').files[0],excels=[...($('#uploadExcelFiles').files||[])];if(zip&&excels.length)throw new Error('Usa ZIP o archivos individuales, no ambos al mismo tiempo.');if(zip)await readZip(zip);else if(excels.length)await parseFiles(excels);const missing=expected.filter(x=>!parsedFiles[x.key]);if(missing.length)throw new Error('Faltan archivos: '+missing.map(x=>x.label+'.xlsx').join(', '));const period=await checkPeriod();let overwrite=false;if(period.existe){overwrite=window.confirm('⚠️ Este periodo ya contiene información ('+period.periodo+').\n\nSi continúas, se reemplazarán las cuatro pestañas históricas de ese periodo y se actualizarán las pestañas operativas actuales.\n\n¿Deseas reemplazar la información?');if(!overwrite){msg('Carga cancelada. No se modificó información.');return}}
      const payload={accion:'admin_cargar_mes',token:session.token,mes:Number($('#uploadMonth').value),anio:Number($('#uploadYear').value),confirmarReemplazo:overwrite,archivos:{}};expected.forEach(x=>payload.archivos[x.key]=parsedFiles[x.key].rows);msg('Enviando los cuatro reportes a Google Sheets. No cierres esta pantalla…');const result=await apiPost(payload);if(result.requiereConfirmacion){if(!window.confirm(result.mensaje+' ¿Confirmas el reemplazo?')){msg('Carga cancelada.');return}payload.confirmarReemplazo=true;const retry=await apiPost(payload);if(retry.error)throw new Error(retry.mensaje);msg(retry.mensaje,'success')}else{if(result.error)throw new Error(result.mensaje);msg(result.mensaje,'success')}if(typeof toast==='function')toast('Carga mensual completada');if(typeof loadData==='function')await loadData();parsedFiles={};$('#uploadExcelFiles').value='';$('#uploadZipFile').value='';setStatus();
    }catch(err){console.error(err);msg(err.message||'No fue posible cargar los archivos.','error')}finally{btn.disabled=false}}
  document.addEventListener('DOMContentLoaded',()=>{const y=$('#uploadYear');if(y){const now=new Date().getFullYear();for(let v=now-3;v<=now+2;v++){const o=document.createElement('option');o.value=v;o.textContent=v;if(v===now)o.selected=true;y.appendChild(o)}}$('#monthlyUploadForm')?.addEventListener('submit',submit);$('#uploadExcelFiles')?.addEventListener('change',async e=>{try{await parseFiles([...e.target.files]);msg('Archivos leídos. Verifica que estén los cuatro reportes.')}catch(err){msg(err.message,'error')}});$('#uploadZipFile')?.addEventListener('change',async e=>{parsedFiles={};setStatus();if(!e.target.files[0])return;try{await readZip(e.target.files[0]);msg('ZIP leído. Verifica que estén los cuatro reportes.')}catch(err){msg(err.message,'error')}})});
})();
